# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  redis:
#    host: 47.103.37.158
#    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#shiro-redis:
#  enabled: true
#  redis-manager:
#    host: 47.103.37.158:6379
server:
  port: 8081
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
#    token有效时长 7天 单位为秒
    expire: 604800
    header: Authorization

